export const aliases = {
  ButtonsButton: "Button",
  ButtonsDestructive: "DestructiveButton",
  FormsElementsInput: "Input",
  FormsElementsRadio: "Radio",
  FormsElementsCheckbox: "Checkbox",
  FormsElementsTextarea: "Textarea",
  FormsElementsSearch: "Search",
  FormsElementsField: "Field",
  FormsElementsLabel: "Label",
  FormsElementsHelpText: "HelpText",
  FormsElementsError: "FormError",
  FormsFieldsInput: "InputField",
  FormsFieldsTextarea: "TextareaField",
  FormsFieldsCheckbox: "CheckboxField",
  BadgesBadge: "Badge",
  MenusTabsHorizontal: "TabsHorizontal",
  MenusDropDownFrame: "DropDown",
  MenusDropDownItem: "DropDownItem",
};
